# Generated by Django 4.2.6 on 2023-11-06 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userAttributes',
        ),
    ]
