# Generated by Django 4.2.6 on 2024-02-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_delete_userattributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('secret_code', models.CharField(max_length=32, unique=True)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
    ]
